library(lattice)
syears <- 2014:2028
plotindex <- 1:10
pindex2 <- 3:13
pindex <- 2:12
y <- years[plotindex]
yy <- syears[pindex]
par(cex.lab=1.4,cex.axis=1.3,lwd=3)
#windows(record=T,height=8,width=12)
#if (.Platform$OS.type=="windows") windows(height=8,width=12,record=T) else X11(height=8,width=12,record=TRUE)
pdf(file='test2.pdf', height=8, width=12)
plot(y,Tbmsmt[plotindex],type='l',lwd=3.5,ylim=c(0,200000),xlab='Year',ylab='Biomass (mt meats)',main='',cex.axis = 1.3,cex.lab=1.4)
lines(y,gbbmsmt[plotindex],lty=2,lwd=3,col='blue')
lines(y,mabmsmt[plotindex],lty=4,lwd=3,col='darkred')
gcolors <- c('black','blue','darkred')
glines <- c(1,2,4)
regions <- c('All','Georges Bank','Mid-Atlantic')
legend('bottomright',regions,col=gcolors,lty=glines,lwd=3,cex=1.7,bty='n')
#savePlot('newclRegionalBms',type='png')
plot(yy,TF[pindex2],xaxt='n',type='l',lwd=3,xlab='Year',ylab='Fishing mortality',main='',ylim=c(0,0.57),cex.axis = 1.3,cex.lab=1.4)
axis(1,at=yy,cex.axis=1.2)
lines(yy,GBF[pindex2],lty=2,lwd=3,col='blue')
lines(yy,MAF[pindex2],lty=4,lwd=3,col='darkred')
legend('bottomright',regions,col=gcolors,lty=glines,lwd=3,cex=1.7,bty='n')
#savePlot('newclFishingmort',type='png')
plot(yy,TLand[pindex2],xaxt='n',type='l',lwd=3,xlab='Year',ylab='Landings (mt meats)',ylim=c(0,40000),cex.axis = 1.3,cex.lab=1.4)
axis(1,at=yy,cex.axis=1.2)
lines(yy,GBLand[pindex2],lty=2,lwd=3,col='blue')
lines(yy,MALand[pindex2],lty=4,lwd=3,col='darkred')
legend('bottomright',regions,col=gcolors,lty=glines,lwd=3,cex=1.7,bty='n')
#savePlot('newclLandings',type='png')

perc <- c('10%','25%','50%','Mean','75%','90%')
pcol <- c('darkred','blue3','dark green','black','blue3','darkred')
psty <- c(3,2,4,1,2,3)
plot(y,bmsmt[plotindex,3,10],type='l',lwd=3,cex.lab=1.4,cex.axis=1.1,xlab='Year',ylab='Biomass (mt meats)',ylim=c(0,250000),cex.axis = 1.3,cex.lab=1.4)
lines(y,qbms10[plotindex,3,10],lwd=2,lty = 2,col='darkred')
lines(y,qbms90[plotindex,3,10],lwd=2,lty = 2,col='darkred')
lines(y,qbms25[plotindex,3,10],lwd=2,lty = 3,col='blue3')
lines(y,qbms75[plotindex,3,10],lwd=2,lty = 3,col='blue3')
lines(y,qbms50[plotindex,3,10],lwd=2,lty = 4,col='dark green')
legend('bottomright',perc,col = pcol,lty=psty,lwd=3,cex=1.6,bty='n')
#savePlot('newclBmspct',type='png')
#plot(yy,Fn[pindex,3,10],type='l',xaxt='n',lwd=3,cex.lab=1.4,cex.axis=1.1,xlab='Year',ylab='Fishing mortality',ylim=c(0,0.4),cex.axis = 1.3,cex.lab=1.4)
#axis(1,at=yy,cex.axis=1.2)
#lines(yy,qF10[pindex,3,10],lwd=2,lty = 2,col='darkred')
#lines(yy,qF90[pindex,3,10],lwd=2,lty = 2,col='darkred')
#lines(yy,qF25[pindex,3,10],lwd=2,lty = 3,col='blue3')
#lines(yy,qF75[pindex,3,10],lwd=2,lty = 3,col='blue3')
#lines(yy,qF50[pindex,3,10],lwd=2,lty = 4,col='dark green')
#legend('bottomright',perc,col = pcol,lty=psty,lwd=3,cex=1.6,bty='n')
#savePlot('newclFpct',type='png')



plot(yy,catch[pindex2,3,10],xaxt='n',type='l',lwd=3,cex.lab=1.4,cex.axis=1.1,xlab='Year',ylab='Landings (mt meats)',ylim=c(0,45000),cex.axis = 1.3,cex.lab=1.4)
axis(1,at=yy,cex.axis=1.2)
lines(yy,qcatch10[pindex2,3,10],lwd=2,lty = 3,col='darkred')
lines(yy,qcatch90[pindex2,3,10],lwd=2,lty = 3,col='darkred')
lines(yy,qcatch25[pindex2,3,10],lwd=2,lty = 2,col='blue3')
lines(yy,qcatch75[pindex2,3,10],lwd=2,lty = 2,col='blue3')
lines(yy,qcatch50[pindex2,3,10],lwd=2,lty = 4,col='dark green')
legend('bottomright',perc,col = pcol,lty=psty,lwd=3,cex=1.7,bty='n')
#savePlot('base-landingspct',type='png')
plotindex=y-2013
plot(y,bmsmt[plotindex,1,1],type='l',lwd=2,cex.lab=1.4,cex.axis=1.2,xlab='Year',ylab='Biomass (mt meats)',ylim=c(0,30000))
lines(y,bmsmt[plotindex,1,2],lwd=2,col='cyan3')
lines(y,bmsmt[plotindex,1,3],lwd=2,col='dark green') #bmsmt in LI
lines(y,bmsmt[plotindex,1,4],lwd=2,col='red2') #SCC
lines(y,bmsmt[plotindex,1,5],lwd=2,col='dodgerblue3')
lines(y,bmsmt[plotindex,1,6],lwd=2,col='purple3')
lines(y,bmsmt[plotindex,1,7],lwd=2,col='gold4')
legend('topright',bty='n',cex=1.4,c('Hudson Canyon S','Virgina Beach','Elephant Trunk','Delmarva','New York Bight','Long Island','Inshore NYB'),lwd=rep(2,7),col=c('black','cyan3','dark green','red2','dodgerblue3','purple3','gold4'),lty=rep(1,7))
#savePlot('newclMABmsbyregion',type=ifelse(.Platform$OS.type=="windows","pdf","png"))
plot(y,bmsmt[plotindex,2,1],type='l',lwd=2,cex.lab=1.4,cex.axis=1.2,xlab='Year',ylab='Biomass (mt meats)',ylim=c(0,40000))
lines(y,bmsmt[plotindex,2,2],lwd=2,col='cyan3')
lines(y,bmsmt[plotindex,2,3],lwd=2,col='dark green') #bmsmt in LI
lines(y,bmsmt[plotindex,2,4],lwd=2,col='red2') #SCC
lines(y,bmsmt[plotindex,2,5],lwd=2,col='dodgerblue3')
lines(y,bmsmt[plotindex,2,6],lwd=2,col='purple3')
sch = bmsmt[plotindex,2,7]+bmsmt[plotindex,2,8]
lines(y,sch,lwd=2,col='gold4')
lines(y,bmsmt[plotindex,2,9],lwd=2,col='darkred')
lines(y,bmsmt[plotindex,2,13],lwd=2,col='green3')
legend('topleft',bty='n',cex=1.4,c('CLI NA','CLI Acc','CLII NA','CLII Acc','NLS NA','NLS Acc','Sch','NEP','SEP'),lwd=rep(2,7),col=c('black','cyan3','dark green','red2','dodgerblue3','purple3','gold4','darkred','green3'),lty=rep(1,7))
#savePlot('GBBmsbyregion',type='png')
yr = 2015:2028
#plot(base10[-1:-2,3,10]~yr,data=sumbase,type='l',lwd=3,ylab='Landings (mt meats)',ylim=c(0,28000),xlim=c(2016,2025),cex.lab=1.5,xlab='Year')
#lines(na10[-1:-2,3,10]~yr,data=sumna,lwd=3,lty=3,col='darkorange')
#lines(c310[-1:-2,3,10]~yr,data=sum3c,lwd=3,lty=2,col='red4')
#lines(c210[-1:-2,3,10]~yr,data=sum2c,lwd=3,lty=4,col='blue2')
#lines(red10[-1:-2,3,10]~yr,data=sumred,lwd=3,lty=5,col='darkgreen')
#lines(gc10[-1:-2,3,10]~yr,data=sumgc,lwd=3,lty=6,col='purple3')
#legend('bottomright',bty='n',cex=1.8,c('Base run','No action','3 new closures','2 new closures','Reduced F','Extra GC'),lwd=3,lty=c(1,3,2,4,5,6),col=c('black','darkorange','red4','blue2','darkgreen','purple3'))
#savePlot('compareland10',type='png')
#plot(TotLand[-1]~yr,data=base10,type='l',lwd=3,ylab='Landings (mt meats)',ylim=c(0,38000),xlim=c(2015,2025),cex.lab=1.5,xlab='Year')
#lines(TotLand[-1]~Year[-1],data=sumna,lwd=3,lty=3,col='darkorange')
#lines(TotLand[-1]~Year[-1],data=sum3c,lwd=3,lty=2,col='red4')
#lines(TotLand[-1]~Year[-1],data=sum2c,lwd=3,lty=4,col='blue2')
#lines(TotLand[-1]~Year[-1],data=sumred,lwd=3,lty=5,col='darkgreen')
#lines(TotLand[-1]~Year[-1],data=sumgc,lwd=3,lty=6,col='purple3')
#legend('bottomright',bty='n',cex=1.8,c('Base run','No action','3 new closures','2 new closures','Reduced F','Extra GC'),lwd=3,lty=c(1,3,2,4,5,6),col=c('black','darkorange','red4','blue2','darkgreen','purple3'))
#savePlot('compareland',type='png')
#plot(TBotArea[-1]~Year[-1],data=sumbase,type='l',lwd=3,ylab='Area swept (sqnm)',ylim=c(0,3200),xlim=c(2015,2025),cex.lab=1.5,xlab='Year')
#lines(TBotArea[-1]~Year[-1],data=sumna,lwd=3,lty=3,col='darkorange')
#lines(TBotArea[-1]~Year[-1],data=sum3c,lwd=3,lty=2,col='red4')
#lines(TBotArea[-1]~Year[-1],data=sum2c,lwd=3,lty=4,col='blue2')
#lines(TBotArea[-1]~Year[-1],data=sumred,lwd=3,lty=5,col='darkgreen')
#lines(TBotArea[-1]~Year[-1],data=sumgc,lwd=3,lty=6,col='purple3')
#legend('bottomright',bty='n',cex=1.8,c('Base run','No action','3 new closures','2 new closures','Reduced F','Extra GC'),lwd=3,lty=c(1,3,2,4,5,6),col=c('black','darkorange','red4','blue2','darkgreen','purple3'))
#savePlot('comparesweptarea',type='png')
#plot(Tbmsmt[-1]~Year[-1],data=sumbase,type='l',lwd=3,ylab='Biomass (mt meats)',ylim=c(0,210000),xlim=c(2015,2025),cex.lab=1.5,xlab='Year')
#lines(Tbmsmt[-1]~Year[-1],data=sumna,lwd=3,lty=3,col='darkorange')
#lines(Tbmsmt[-1]~Year[-1],data=sum3c,lwd=3,lty=2,col='red4')
#lines(Tbmsmt[-1]~Year[-1],data=sum2c,lwd=3,lty=4,col='blue2')
#lines(Tbmsmt[-1]~Year[-1],data=sumred,lwd=3,lty=5,col='darkgreen')
#lines(Tbmsmt[-1]~Year[-1],data=sumgc,lwd=3,lty=6,col='purple3')
#legend('bottomright',bty='n',cex=1.8,c('Base run','No action','3 new closures','2 new closures','Reduced F','Extra GC'),lwd=3,lty=c(1,3,2,4,5,6),col=c('black','darkorange','red4','blue2','darkgreen','purple3'))
#savePlot('comparebms',type='png')





#plot(Tbmsmt~Year,data=basesum,type='l',lwd=3,ylab='Biomass (mt meats)',ylim=c(0,200000),xlim=c(2014,2025),cex.lab=1.5)
#lines(Tbmsmt~Year,data=newclsum,lwd=3,lty=2,col='red4')
#lines(Tbmsmt~Year,data=reducedsum,lwd=3,lty=2,col='blue2')
legend('bottomright',bty='n',cex=1.8,c('Base run','New closure','Reduced F'),lwd=3,lty=c(1,2,4),col=c('black','red4','blue2'))
#savePlot('bmscompare',type='png')
